# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password: root

# development:
#   <<: *default
#   database: expense_tracker_development

# test:
#   <<: *default
#   database: expense_tracker_test

# production:
#   <<: *default
#   database: expense_tracker_production
#   username: readers_club
#   password: <%= ENV['READERS_CLUB_DATABASE_PASSWORD'] %>

##-----------------------------------------------------------------
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: et_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: et_test
  username: postgres
  password: postgresdb

production:
  <<: *default
  database: et_production
  username: postgres
  password: postgresdb